[package]
name = "bevy_editor_pls_default_windows"
version.workspace = true
edition.workspace = true
license.workspace = true
#repository.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
bevy = { version = "0.11", default-features = false, features = [
    "bevy_scene",
    "bevy_text",
    "bevy_ui",
    "bevy_sprite",
    "bevy_pbr",
    "bevy_core_pipeline",
] }
bevy_editor_pls_core.workspace = true
bevy-inspector-egui.workspace = true
indexmap = "2"
pretty-type-name = "1.0"
bevy_mod_debugdump = "0.8"
opener = "0.6.0"
egui-gizmo.workspace = true
